[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.0.0",
    "gspread>=6.2.1",
    "oauth2client>=4.1.3",
]
